# either rename this file to config.ini or remove "example" from this file name
# to get discord webhook, right click on the channel you want to post your results and go to edit channel
# click on integrations, click on Webhook
# click add. Name the webhook and copy the url
# add webbhook surrounded by "" and change false to true
# save the file
[Discord]
Enabled=false
WebhookUrl=